version: "3"
services:
  web:
    build: .
    expose:
      - 8000
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    command: gunicorn --config=gunicorn_config.py cinemix.wsgi:application
    depends_on:
      - db
    env_file: .env
    environment:
      - DEBUG=FALSE
  db:
    image: postgres:10-alpine
    ports:
      - '5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  nginx:
    restart: always
    build: ./server
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: