# Generated by Django 2.2.8 on 2019-12-24 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('year', models.PositiveSmallIntegerField()),
                ('runtime', models.PositiveSmallIntegerField()),
                ('image', models.ImageField(blank=True, upload_to='img/')),
                ('trailer', models.URLField(blank=True)),
                ('video1', models.URLField(blank=True)),
                ('video2', models.URLField(blank=True)),
                ('plot', models.TextField()),
                ('imdb', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('kinopoisk', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('watched', models.BooleanField(default=False)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('actors', models.ManyToManyField(to='movie.Actor')),
                ('categories', models.ManyToManyField(blank=True, to='movie.Category')),
                ('countries', models.ManyToManyField(to='movie.Country')),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movie.Director')),
                ('genres', models.ManyToManyField(to='movie.Genre')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movie.MovieType')),
            ],
            options={
                'ordering': ['-added'],
            },
        ),
    ]
