# Generated by Django 2.2.8 on 2020-01-08 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_movie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['title'], 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='director',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['title']},
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('movie', models.ManyToManyField(blank=True, related_name='collections', to='movie.Movie')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
